### ISSUE TITLE
Modupdater error on this mod

### ISSUE THREAD

**Issue by NoxiousPluK** [Nauja/raft-mods#1]
Hi!

When trying to check for updates for this mod in Modupdater (https://github.com/FranzFischer78/ModUpdater), I get this in the log (and a yellow version tag):
```
[Modupdater] Check for Updates for Inifinite Use
[Modupdater] Mod not found on Raftmodding Server. Is it one of yours? If not it may be misconfigured. Update the mod manually and ping me and the author... Raft is not Shark Food and Lantern Physics got this issue.
```

**Comment by Nauja** [comment]
Hi, thanks for reporting that, I'm going to take a look

**Comment by Nauja** [comment]
I have updated the URL in modinfo.json, it should now be working. Thanks again for reporting :)
